name: CI/CD GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python -m pip install --upgrade pip
      - run: pip install pytest
      - run: pip install pytest-cov
      - run: pip install coveralls
      # - run: pip install python-coveralls
      - run: pip install pytest-xdist
      - run: pip install pytest-black
      - run: coverage run ./equation_test.py

      - name: Coveralls
        run: COVERALLS_REPO_TOKEN=${{ secrets.coveralls_token }} coveralls 



  # sonarcloud:
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python }}
  #     - name: Install tox and any other packages
  #       run: pip install tox
  #     - name: Run tox
  #       run: tox -e py
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}