name: CI/CD GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install coveralls
      # - run: pip install python-coveralls
      # - run: pip install pytest-xdist
      # - run: pip install pytest-black
      - run: coverage run ./equation_test.py

      - name: Coveralls
        run: COVERALLS_REPO_TOKEN=${{ secrets.coveralls_token }} coveralls