name: CI/CD GitHub Actions
on: [push]
jobs:
  gtest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip uninstall python-coveralls
      - run: pip install coveralls
      - run: coverage run ./equation_test.py

      - name: Coveralls
        run: COVERALLS_REPO_TOKEN=${{ secrets.coveralls_token }} coveralls