name: CI/CD GitHub Actions
on: [push]
jobs:
  gtest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install coveralls
      - run: python3 ./equation_test.py

      - name: Coveralls
        run: python3 coveralls -t ${{ secrets.coveralls_token }} --root . -E ".*external.*" -E ".*tests.*"